//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudAlumnos.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Alumno
    {
        
        public int Id { get; set; }
        [Required]

        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public Nullable<int> Edad { get; set; }
        public string Genero { get; set; }
        public System.DateTime FechaRegistro { get; set; }
    }
}
